import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BlurryBg from "./blurbg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ProductStudio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative">
        <div className="absolute p-6 z-10 text-gray-900">
          <h1 className="  font-bold text-lg">Product Studio</h1>
          <p className="text-sm">
            Building Resilient Digital Products for the next generation.
          </p>
        </div>
        <div className="absolute top-0 left-0 z-0">
          <BlurryBg />
        </div>
      </div>
    </div>
  );
}
